import type { CSSProperties } from 'react';

export const passportStyles = {
  container: {
    width: '100%',
    maxWidth: '800px',
    margin: '0 auto',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  backButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    background: 'rgba(255, 255, 255, 0.9)',
    border: '1px solid rgba(226, 232, 240, 0.6)',
    borderRadius: '8px',
    color: '#64748b',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    backdropFilter: 'blur(10px)',
  },
  headerTitle: {
    fontSize: '1.5rem',
    fontWeight: '600',
    color: '#1e293b',
    margin: '0',
  },
  card: {
    background: 'rgba(255, 255, 255, 0.9)',
    backdropFilter: 'blur(20px)',
    borderRadius: '20px',
    padding: '2rem',
    boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
    border: '1px solid rgba(226, 232, 240, 0.6)',
  },
  itemHeader: {
    display: 'flex',
    gap: '1.5rem',
    marginBottom: '2rem',
    alignItems: 'flex-start',
  },
  itemImage: {
    width: '80px',
    height: '80px',
    borderRadius: '12px',
    overflow: 'hidden',
    flexShrink: '0',
  },
  placeholderImage: {
    width: '100%',
    height: '100%',
    background: 'linear-gradient(135deg, #f1f5f9, #e2e8f0)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#64748b',
  },
  itemInfo: {
    flex: '1',
  },
  itemTitle: {
    fontSize: '1.5rem',
    fontWeight: '600',
    color: '#1e293b',
    margin: '0 0 0.5rem',
  },
  itemDescription: {
    color: '#64748b',
    margin: '0 0 1rem',
    lineHeight: '1.5',
  },
  itemMeta: {
    display: 'flex',
    gap: '1rem',
    fontSize: '0.875rem',
    color: '#64748b',
  },
  tabs: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '2rem',
    borderBottom: '1px solid #e2e8f0',
  },
  tab: {
    padding: '0.75rem 1.5rem',
    background: 'none',
    border: 'none',
    color: '#64748b',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    position: 'relative' as const,
  },
  tabActive: {
    color: '#3b82f6',
  },
  tabContent: {
    minHeight: '200px',
  },
  infoSection: {
    marginBottom: '2rem',
  },
  infoSectionTitle: {
    fontSize: '1.125rem',
    fontWeight: '600',
    color: '#1e293b',
    margin: '0 0 1rem',
  },
  infoGrid: {
    display: 'grid',
    gap: '1rem',
  },
  infoItem: {
    display: 'grid',
    gridTemplateColumns: '200px 1fr',
    alignItems: 'start',
    columnGap: '1.5rem',
    rowGap: '0.25rem',
    padding: '0.75rem 0',
    borderBottom: '1px solid #f1f5f9',
  },
  infoItemMobile: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    gap: '0.5rem',
    padding: '0.75rem 0',
    borderBottom: '1px solid #f1f5f9',
  },
  label: {
    fontWeight: '500',
    color: '#64748b',
    paddingTop: '0.125rem',
  },
  value: {
    color: '#1e293b',
    fontWeight: '500',
    lineHeight: '1.6',
    wordBreak: 'break-word',
    whiteSpace: 'pre-wrap',
  } as CSSProperties,
  status: {
    fontWeight: '600',
  },
};

// Timeline specific styles
export const timelineStyles = {
  container: {
    position: 'relative' as const,
    paddingLeft: '2rem',
  },
  line: {
    position: 'absolute' as const,
    left: '0.75rem',
    top: '0',
    bottom: '0',
    width: '2px',
    background: '#e2e8f0',
  },
  item: {
    position: 'relative' as const,
    marginBottom: '1.5rem',
  },
  dot: {
    position: 'absolute' as const,
    left: '-2rem',
    top: '0.25rem',
    width: '1rem',
    height: '1rem',
    background: '#3b82f6',
    borderRadius: '50%',
    border: '3px solid white',
    boxShadow: '0 0 0 2px #e2e8f0',
  },
  card: {
    position: 'relative' as const,
    background: '#f8fafc',
    borderRadius: '12px',
    padding: '1rem',
    paddingTop: '0.75rem',
    borderLeft: '4px solid #3b82f6',
  },
  emptyState: {
    textAlign: 'center' as const,
    padding: '3rem 2rem',
    color: '#64748b',
  },
  emptyIcon: {
    width: '4rem',
    height: '4rem',
    margin: '0 auto 1rem',
    background: '#f1f5f9',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#94a3b8',
  },
};
